apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: store
  namespace: external
  annotations:
    kubernetes.io/ingress.class: "addon-http-application-routing"
spec:
  rules:
  - host: store.CLUSTER_PUBLIC_URL
    http:
      paths:
      - path: /api
        backend:
         serviceName: storeapigateway
         servicePort: 80
      - path: /
        backend:
          serviceName: storefront
          servicePort: 80